### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by mrossi93** [ltebs-polimi/AY2021_Project_1-2#1]
A .gitignore should be present in the repository, otherwise all unnecessary files will be uploaded.

**Comment by Nunzio117** [comment]
thanks!

**Comment by mp1994** [comment]
The `.gitignore` has been added to the repository, but files that should be ignored are still present.

To make the `.gitignore` effective, you need to untrack the files that were added to the repo before the `.gitignore` was created. This is done with: 

    git rm -r --cached .
    git add .

The first command will remove (`rm`) from the index (`--cached`) all the files, recursively (`-r`). This will not remove the _physical_ files in your folder. The second one will add everything back to the index, this time ignoring the files as specified in the `.gitignore`.
You can also manually do `git rm --cached <file>` for all the files that should be untracked, with no need to add back everything (useful to remove a single file/folder from a large repository)

**Comment by Nunzio117** [comment]
Thanks!

**Comment by Nunzio117** [comment]
Buongiorno, comunque nel applicare tale comando: "git rm -r --cached" esce
quanto riportato nell'immagine allegata alla mail. Ho ben capito che posso
scegliere manualmente quale cartella togliere, ma dopo il primo suo avviso,
avevo già eliminato la cartella Design01 per mettere poi .gitignore e la
cartella di nuovo sulla repository, infatti nella cartella Design01 ora non
ci sono più cartelle anomale come prima. Quindi ora non capisco quali altri
file non vadano bene

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 30 nov 2020 alle ore 12:11 mp1994 <notifications@github.com>
ha scritto:

**Comment by mp1994** [comment]
Nella root della repository ci sono file .cywrk.*

**Comment by Nunzio117** [comment]
ah va bene allora procederò con i comandi consigliati dalla sua mail
precedente ma in maniera selettiva. Grazie!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 30 nov 2020 alle ore 17:14 mp1994 <notifications@github.com>
ha scritto:
